package in.coderinfotech.batchschedule;
// Generated Jan 22, 2018 5:23:28 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;

import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AcademicDetails generated by hbm2java
 */
@Entity
@Table(name = "academic_details")
public class AcademicDetails implements java.io.Serializable {

	private long academicDetailsId;
	private String graduation;
	private String graduationPercentage;
	private String graduationYear;
	private String graduationDuration;
	private String masterDegree;
	private String masterPercentage;
	private String masterYear;
	private String masterDuration;
	private String diploma;
	private Set<PersonDetails> personDetailses = new HashSet<PersonDetails>(0);

	public AcademicDetails() {
	}

	public AcademicDetails(long academicDetailsId) {
		this.academicDetailsId = academicDetailsId;
	}

	public AcademicDetails(long academicDetailsId, String graduation, String graduationPercentage,
			String graduationYear, String graduationDuration, String masterDegree, String masterPercentage,
			String masterYear, String masterDuration, String diploma, Set<PersonDetails> personDetailses) {
		this.academicDetailsId = academicDetailsId;
		this.graduation = graduation;
		this.graduationPercentage = graduationPercentage;
		this.graduationYear = graduationYear;
		this.graduationDuration = graduationDuration;
		this.masterDegree = masterDegree;
		this.masterPercentage = masterPercentage;
		this.masterYear = masterYear;
		this.masterDuration = masterDuration;
		this.diploma = diploma;
		this.personDetailses = personDetailses;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "ACADEMIC_DETAILS_ID", unique = true, nullable = false)
	public long getAcademicDetailsId() {
		return this.academicDetailsId;
	}

	public void setAcademicDetailsId(long academicDetailsId) {
		this.academicDetailsId = academicDetailsId;
	}

	@Column(name = "GRADUATION", length = 35)
	public String getGraduation() {
		return this.graduation;
	}

	public void setGraduation(String graduation) {
		this.graduation = graduation;
	}

	@Column(name = "GRADUATION_PERCENTAGE", length = 35)
	public String getGraduationPercentage() {
		return this.graduationPercentage;
	}

	public void setGraduationPercentage(String graduationPercentage) {
		this.graduationPercentage = graduationPercentage;
	}

	@Column(name = "GRADUATION_YEAR", length = 35)
	public String getGraduationYear() {
		return this.graduationYear;
	}

	public void setGraduationYear(String graduationYear) {
		this.graduationYear = graduationYear;
	}

	@Column(name = "GRADUATION_DURATION", length = 35)
	public String getGraduationDuration() {
		return this.graduationDuration;
	}

	public void setGraduationDuration(String graduationDuration) {
		this.graduationDuration = graduationDuration;
	}

	@Column(name = "MASTER_DEGREE", length = 35)
	public String getMasterDegree() {
		return this.masterDegree;
	}

	public void setMasterDegree(String masterDegree) {
		this.masterDegree = masterDegree;
	}

	@Column(name = "MASTER_PERCENTAGE", length = 35)
	public String getMasterPercentage() {
		return this.masterPercentage;
	}

	public void setMasterPercentage(String masterPercentage) {
		this.masterPercentage = masterPercentage;
	}

	@Column(name = "MASTER_YEAR", length = 35)
	public String getMasterYear() {
		return this.masterYear;
	}

	public void setMasterYear(String masterYear) {
		this.masterYear = masterYear;
	}

	@Column(name = "MASTER_DURATION", length = 35)
	public String getMasterDuration() {
		return this.masterDuration;
	}

	public void setMasterDuration(String masterDuration) {
		this.masterDuration = masterDuration;
	}

	@Column(name = "DIPLOMA", length = 500)
	public String getDiploma() {
		return this.diploma;
	}

	public void setDiploma(String diploma) {
		this.diploma = diploma;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "academicDetails")
	public Set<PersonDetails> getPersonDetailses() {
		return this.personDetailses;
	}

	public void setPersonDetailses(Set<PersonDetails> personDetailses) {
		this.personDetailses = personDetailses;
	}

	@Override
	public String toString() {
		return "AcademicDetails [academicDetailsId=" + academicDetailsId + ", graduation=" + graduation
				+ ", graduationPercentage=" + graduationPercentage + ", graduationYear=" + graduationYear
				+ ", graduationDuration=" + graduationDuration + ", masterDegree=" + masterDegree
				+ ", masterPercentage=" + masterPercentage + ", masterYear=" + masterYear + ", masterDuration="
				+ masterDuration + ", diploma=" + diploma + ", personDetailses=" + personDetailses + "]";
	}

}
