package in.coderinfotech.batchschedule;
// Generated Jan 22, 2018 5:23:28 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StateMst generated by hbm2java
 */
@Entity
@Table(name = "state_mst")
public class StateMst implements java.io.Serializable {

	private long stateId;
	private String stateCode;
	private String stateName;
	private Set<PersonDetails> personDetailses = new HashSet<PersonDetails>(0);
	private Set<CityMst> cityMsts = new HashSet<CityMst>(0);

	public StateMst() {
	}

	public StateMst(long stateId) {
		this.stateId = stateId;
	}

	public StateMst(long stateId, String stateCode, String stateName, Set<PersonDetails> personDetailses,
			Set<CityMst> cityMsts) {
		this.stateId = stateId;
		this.stateCode = stateCode;
		this.stateName = stateName;
		this.personDetailses = personDetailses;
		this.cityMsts = cityMsts;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "STATE_ID", unique = true, nullable = false)
	public long getStateId() {
		return this.stateId;
	}

	public void setStateId(long stateId) {
		this.stateId = stateId;
	}

	@Column(name = "STATE_CODE", length = 35)
	public String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}

	@Column(name = "STATE_NAME", length = 35)
	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stateMst")
	public Set<PersonDetails> getPersonDetailses() {
		return this.personDetailses;
	}

	public void setPersonDetailses(Set<PersonDetails> personDetailses) {
		this.personDetailses = personDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stateMst")
	public Set<CityMst> getCityMsts() {
		return this.cityMsts;
	}

	public void setCityMsts(Set<CityMst> cityMsts) {
		this.cityMsts = cityMsts;
	}

	@Override
	public String toString() {
		return "StateMst [stateId=" + stateId + ", stateCode=" + stateCode + ", stateName=" + stateName
				+ ", personDetailses=" + personDetailses + ", cityMsts=" + cityMsts + "]";
	}

}
