package in.coderinfotech.batchschedule;
// Generated Jan 22, 2018 5:23:28 PM by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TrainerDetails generated by hbm2java
 */
@Entity
@Table(name = "trainer_details")
public class TrainerDetails implements java.io.Serializable {

	private long trainerDetailsId;
	private PersonDetails personDetails;
	private String trainerCode;
	private String title;
	private String areasOfSpecialization;
	private String department;
	private String officeLocation;
	private String officeTelephone;
	private String experience;
	private String researchInterests;
	private String projects;

	public TrainerDetails() {
	}

	public TrainerDetails(long trainerDetailsId) {
		this.trainerDetailsId = trainerDetailsId;
	}

	public TrainerDetails(long trainerDetailsId, PersonDetails personDetails, String trainerCode, String title,
			String areasOfSpecialization, String department, String officeLocation, String officeTelephone,
			String experience, String researchInterests, String projects) {
		this.trainerDetailsId = trainerDetailsId;
		this.personDetails = personDetails;
		this.trainerCode = trainerCode;
		this.title = title;
		this.areasOfSpecialization = areasOfSpecialization;
		this.department = department;
		this.officeLocation = officeLocation;
		this.officeTelephone = officeTelephone;
		this.experience = experience;
		this.researchInterests = researchInterests;
		this.projects = projects;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "TRAINER_DETAILS_ID", unique = true, nullable = false)
	public long getTrainerDetailsId() {
		return this.trainerDetailsId;
	}

	public void setTrainerDetailsId(long trainerDetailsId) {
		this.trainerDetailsId = trainerDetailsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRAINER_PERSON_DETAILS_ID")
	public PersonDetails getPersonDetails() {
		return this.personDetails;
	}

	public void setPersonDetails(PersonDetails personDetails) {
		this.personDetails = personDetails;
	}

	@Column(name = "TRAINER_CODE", length = 35)
	public String getTrainerCode() {
		return this.trainerCode;
	}

	public void setTrainerCode(String trainerCode) {
		this.trainerCode = trainerCode;
	}

	@Column(name = "TITLE", length = 35)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "AREAS_OF_SPECIALIZATION", length = 65535)
	public String getAreasOfSpecialization() {
		return this.areasOfSpecialization;
	}

	public void setAreasOfSpecialization(String areasOfSpecialization) {
		this.areasOfSpecialization = areasOfSpecialization;
	}

	@Column(name = "DEPARTMENT", length = 35)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "OFFICE_LOCATION", length = 35)
	public String getOfficeLocation() {
		return this.officeLocation;
	}

	public void setOfficeLocation(String officeLocation) {
		this.officeLocation = officeLocation;
	}

	@Column(name = "OFFICE_TELEPHONE", length = 35)
	public String getOfficeTelephone() {
		return this.officeTelephone;
	}

	public void setOfficeTelephone(String officeTelephone) {
		this.officeTelephone = officeTelephone;
	}

	@Column(name = "EXPERIENCE", length = 50)
	public String getExperience() {
		return this.experience;
	}

	public void setExperience(String experience) {
		this.experience = experience;
	}

	@Column(name = "RESEARCH_INTERESTS", length = 65535)
	public String getResearchInterests() {
		return this.researchInterests;
	}

	public void setResearchInterests(String researchInterests) {
		this.researchInterests = researchInterests;
	}

	@Column(name = "PROJECTS", length = 65535)
	public String getProjects() {
		return this.projects;
	}

	public void setProjects(String projects) {
		this.projects = projects;
	}

	@Override
	public String toString() {
		return "TrainerDetails [trainerDetailsId=" + trainerDetailsId + ", personDetails=" + personDetails
				+ ", trainerCode=" + trainerCode + ", title=" + title + ", areasOfSpecialization="
				+ areasOfSpecialization + ", department=" + department + ", officeLocation=" + officeLocation
				+ ", officeTelephone=" + officeTelephone + ", experience=" + experience + ", researchInterests="
				+ researchInterests + ", projects=" + projects + "]";
	}

}
